config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root "pins#index"
  get "about" => "pages#about"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => {:medium => "400x400>", :thumb => "100x100>"}
	validates_attachment :image, presence: true, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
	validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:email]
  
  has_many :pins, dependent: :destroy

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_h).first
    end
  end

  validates :username, 
    :presence => true, 
    :uniqueness => {
    	:case_sensitive => false
    }
  
  validates :username, 
    :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_filter :configure_permitted_parameters, if: :devise_controller?

protected
    
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
  
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin successfully created'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin successfully updated'
    else
      render action: 'edit'
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    redirect_to pins_url, notice: 'Pin successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      if @pin.user == current_user
        @pin = current_user.pins.find_by(id: params[:id])
      else  
        redirect_to pins_path, notice: "That's not your pin!"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" <%=link_to "Mending.Me", root_path %> </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li> 
        <% if user_signed_in? %>
          <li><%= link_to "New Pin", new_pin_path %></li>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %> </li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path%></li>
          <li><%= link_to "Sign Up", new_user_registration_path%></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mending.Me</title>
  <%= stylesheet_link_tag'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<div class="container">
    <%= yield %>
</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
	<h1>Mending.Me</h1>
	<% if user_signed_in? %>
		<div class="jumbotron white">
			<%= link_to "Latest Pins", pins_path, class: "btn btn-primary btn-lg" %>
		</div>
	<% else %>
		<p>
			<%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>
			<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
		</p>
	<% end %>
</div>

app/views/pages/about.html.erb
<h1>About Mending Me</h1>
<p>I am working on mending</p>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Mending.Me</h1>
	<% if user_signed_in? %>
		<div class="jumbotron white">
			<%= link_to "Latest Pins", pins_path, class: "btn btn-primary btn-lg" %>
		</div>
	<% else %>
		<p>
			<%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>
			<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
		</p>
	<% end %>
</div>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<p id="notice"><%= notice %></p>

<div id="add">
<h1>Latest Pins</h1>
<% if user_signed_in? %>
  <%= link_to 'New Pin', new_pin_path, class: "btn btn-primary btn-block" %>
<% end %>
</div>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <p><strong><%= pin.description %></strong></p>
        <p><%= pin.user.username if pin.user %></p>
        <%= link_to pin_path(pin) do %>
          <span class="glyphicon glyphicon-resize-full" aria-hidden="true"></span>
        <% end %>
        <% if current_user && pin.user == current_user %>
          <%= link_to edit_pin_path(pin) do %>
            <span class="glyphicon glyphicon-edit"></span>
          <% end %>
          <%= link_to pin, method: :delete, data: { confirm: 'Are you sure you want to delete this pin?' } do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="center">
  <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

<div id="add">
<% if user_signed_in? %>
  <%= link_to 'New Pin', new_pin_path, class: "btn btn-primary btn-block" %>
<% end %>
</div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to pins_path do%>
	<span class="glyphicon glyphicon-arrow-left"></span>
	Back
<% end %> 

<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class="panel panel-center">
				<%= image_tag @pin.image.url(:medium) %>
			</div>
			<div class="panel-body">
				<p><strong><%= @pin.description%></strong></p>
				<p><%= @pin.user.username if @pin.user%></p>
				<% if current_user && @pin.user == current_user %>
  					<%= link_to edit_pin_path(@pin) do %> 
  						<span class="glyphicon glyphicon-edit"></span>
  					<% end %> 
  					<%= link_to @pin, method: :delete, data: { confirm: 'Are you sure you want to delete this pin?' } do %>
  						<span class="glyphicon glyphicon-trash"></span>
  					<% end %> 
				<% end %>
			</div>
		</div>
	</div>
</div>